org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.experimental.privacysandbox.sdk.enable=false

# Performance and modern defaults
android.dependency.useConstraints=false

# Speed up build
org.gradle.parallel=true
org.gradle.configuration-cache=true
